dashboard/apps/udb/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^admin', views.admin, name = 'admin'),
    url(r'^dashboard', views.dashboard, name='dashboard'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^', views.index, name = 'index'),
]

dashboard/apps/users/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'show(?P<user_id>[0-9])', views.show, name = 'show'),
    url(r'delete/(?P<user_id>[0-9])', views.delete, name = 'delete'),
    url(r'update', views.update, name = 'update'),
    url(r'edit/(?P<user_id>[0-9])', views.edit, name = 'edit'),
    url(r'^create', views.create, name = 'create'),
    url(r'^login', views.login, name = 'login'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^new', views.new, name = 'new'),
    url(r'^signin', views.signin, name = 'signin'),
    url(r'^comment', views.comment, name = 'comment'),
    url(r'^post', views.post, name = 'post'),
]

dashboard/dashboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^users/', include('apps.users.urls', namespace = 'users')),
    url(r'^', include('apps.udb.urls', namespace = 'udb')),
]

dashboard/apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import re
import bcrypt

class UserManager(models.Manager):
    def registration_validator(self,postData):
        errors = {}
        #!!!!!Check if user already exists!!!
        emailsearch = User.objects.filter(email = postData['email'])
        if len(emailsearch)>0:
            errors['email'] = 'Account already exists'
        #ensure first and last name contain only letters
        if not re.match(r'^[a-zA-Z]+$', postData['first']):
            errors['first'] = 'First name can only contain letters'
        if not re.match(r'^[a-zA-Z]+$', postData['last']):
            errors['last'] = 'Last name can only contain letters'
        #check if first name is at least one character long
        if len(postData['first'])<1:
            errors['first'] = "First name required"
        #check that passwords match
        if len(postData['pwd']) < 8:
            errors['password_length'] = "Passwords must be at least 8 characters long"
        if postData['pwd'] != postData['cpw']:
            errors['password'] = "Confirmation did not match password"
        #check if last name is at least two characters long
        if len(postData['last'])<2:
            errors['last'] = "Last name too short"
        if len(postData['last'])<1:
            errors['last'] = "Last name required"
        return errors
    def update_validator(self,postData):
        errors = {}
        #!!!!!Check if user already exists!!!
        #ensure first and last name contain only letters
        if not re.match(r'^[a-zA-Z]+$', postData['first']):
            errors['first'] = 'First name can only contain letters'
        if not re.match(r'^[a-zA-Z]+$', postData['last']):
            errors['last'] = 'Last name can only contain letters'
        #check if first name is at least one character long
        if len(postData['first'])<1:
            errors['first'] = "First name required"
        #check if last name is at least two characters long
        if len(postData['last'])<1:
            errors['last'] = "Last name required"
        elif len(postData['last'])<2:
            errors['last'] = "Last name too short"
        #check that passwords match
        if postData['pwd'] != postData['cpw']:
            errors['password'] = "Confirmation did not match password"
        if postData['pwd'] < 8 and postData['pwd'] > 0:
            errors['password'] = "Passwords must be at least 8 characters long"
        return errors
    def login_validator(self,postData):
        errors = {}
        #check if user exists
        email = postData['email']
        emailsearch = User.objects.filter(email = email)
        if len(emailsearch) < 1:
            errors['email']='User not found'
        #verify password
        else:
            pwd = postData['pwd']
            temp = User.objects.get(email = email)
            hashedpw = temp.password
            if not bcrypt.checkpw(pwd.encode(), hashedpw.encode()):
                errors['password']='Unable to authenticate'
        return errors

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    email = models.CharField(max_length = 255)
    password = models.CharField(max_length = 255)
    user_level = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()
class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts")
    poster = models.ForeignKey(User, related_name="postings")
    post = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments")
    commenter = models.ForeignKey(User, related_name="commentings")
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

dashboard/apps/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponseRedirect, HttpResponse, redirect
from django.contrib import messages
from .forms import LoginForm, RegistrationForm
from .models import User, Post, Comment
import bcrypt

# Create your views here.
def new(request):
    #start the journey
    register = RegistrationForm()
    return render(request, 'users/new.html', {'register': register})
def signin(request):
    #start the journey
    login = LoginForm()
    return render(request, 'users/login.html', {'login':login})
def create(request):
    errors = User.objects.registration_validator(request.POST)
    if len(errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('users:new')
    else:
    #process registration form to add an account
        fname = request.POST['first']
        lname = request.POST['last']
        email = request.POST['email']
        pwd = request.POST['pwd']
        cpw = request.POST['cpw']
        hash1 = bcrypt.hashpw(pwd.encode(), bcrypt.gensalt())
        print hash1
        print bcrypt.checkpw(cpw.encode(), hash1)
        admin = User.objects.filter(user_level = 9)
        if admin.count() < 1:
            User.objects.create(first_name = fname, last_name = lname, email = email, user_level = 9, password = hash1)
        else:
            User.objects.create(first_name = fname, last_name = lname, email = email, user_level = 1, password = hash1)
        temp = User.objects.get(email = email)
        request.session['id'] = temp.id
        request.session['level'] = temp.user_level
        level = temp.user_level
        if level > 5:
            return redirect('/admin_dashboard')
        else:
            return redirect('/dashboard')
def login(request):
    # process login form
    errors = User.objects.login_validator(request.POST)
    if len(errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('users:signin')
    else:
        email = request.POST['email']
        temp = User.objects.get(email = email)
        request.session['id'] = temp.id
        request.session['level'] = temp.user_level
        print request.session['id']
        level = temp.user_level
        if level > 5:
            return redirect('/admin_dashboard')
        else:
            return redirect('/dashboard')
def logout(request):
    del request.session['id']
    return redirect('/')
def show(request, user_id):
    context = {
        'id': request.session['id'],
        'user': User.objects.get(id=user_id),
        'posts': Post.objects.filter(user_id=user_id),
        'comments': Comment.objects.all(),
    }
    return render(request, 'users/profile.html', context)
def delete(request, user_id):
    user = User.objects.get(id=user_id)
    admin = User.objects.filter(user_level = 9)
    if admin.count() < 2 and user.user_level >5:
        return HttpResponse('Unable to delete final admin.')
    elif user.id == request.session['id']:
        user.delete()
        del request.session['id']
        return redirect('/')
    else:
        user.delete()
        return redirect('/admin_dashboard')
def edit(request, user_id):
    register = RegistrationForm()
    context = {
        'user': User.objects.get(id = user_id),
        'register': register,
    }
    level = request.session['level']
    if level > 5:
        return render(request, 'users/admin_edit.html', context)
    else:
        return render(request, 'users/edit.html', context)
def update(request):
    errors = User.objects.update_validator(request.POST)
    user_id = request.POST['user_id']
    if len(errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('users/edit/%s' %user_id)
    else:
        lvl = request.session['level']
        if lvl > 5:
            #process registration form to update an account
            fname = request.POST['first']
            lname = request.POST['last']
            email = request.POST['email']
            pwd = request.POST['pwd']
            cpw = request.POST['cpw']
            user_id = request.POST['user_id']
            hash1 = bcrypt.hashpw(pwd.encode(), bcrypt.gensalt())
            print hash1
            print bcrypt.checkpw(cpw.encode(), hash1)
            temp = User.objects.get(id = user_id)
            desc = request.POST['desc']
            if desc > 1:
                temp.description = desc
                temp.save()
            if len(cpw)>0:
                if request.POST['user_level'] == 'admin':
                    level = 9
                else:
                    level = 1
                temp.first_name = fname
                temp.last_name = lname
                temp.email = email
                temp.user_level = level
                temp.password = hash1
                temp.save()
            else:
                temp.first_name = fname
                temp.last_name = lname
                temp.email = email
                temp.user_level = level
                temp.save()
            return redirect('/admin_dashboard')
        else:
            fname = request.POST['first']
            lname = request.POST['last']
            email = request.POST['email']
            pwd = request.POST['pwd']
            cpw = request.POST['cpw']
            desc = request.POST['desc']
            user_id = request.POST['user_id']
            hash1 = bcrypt.hashpw(pwd.encode(), bcrypt.gensalt())
            temp = User.objects.get(id = user_id)
            if len(desc)>1:
                temp.description = desc
                temp.save()
            if len(cpw)>0:
                temp.first_name = fname
                temp.last_name = lname
                temp.email = email
                temp.password = hash1
                temp.save()
            else:
                temp.first_name = fname
                temp.last_name = lname
                temp.email = email
                temp.save()
            return redirect('/dashboard')

def post(request):
    post= request.POST['post']
    user_pk = request.POST['user_id']
    user_id= User.objects.get(id=user_pk)
    poster_pk = request.session['id']
    poster= User.objects.get(id=poster_pk)
    Post.objects.create(user = user_id, poster = poster, post = post)
    return redirect('/users/show%s' %user_pk)
def comment(request):
    comment = request.POST['comment']
    post_pk = request.POST['post_id']
    post = Post.objects.get(id=post_pk)
    commenter_pk = request.session['id']
    commenter= User.objects.get(id=commenter_pk)
    user_pk = request.POST['user_id']
    Comment.objects.create(commenter = commenter, post = post, comment = comment)
    return redirect('/users/show%s' %user_pk)

dashboard/apps/users/templates/users/admin_edit.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User Dashboard Assignment</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css ">
  </head>
  <body>
    <nav class='navbar navbar-default'>
      <h1>User Dashboard</h1>
      <a href="/admin_dashboard">Home</a>
      <a class = 'navbar-right' href="{%url 'users:logout'%}">Sign Out</a>
    </nav>
    <h1>Edit profile for user # {{user.id}}</h1>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    <form action="{% url 'users:update'%}" method="post">
        {% csrf_token %}
      <p>First Name: <input type="text" name="first" value="{{user.first_name}}"></p>
      <p>Last Name: <input type="text" name="last" value="{{user.last_name}}"></p>
      <p>Email: <input type="email" name="email" value="{{user.email}}"></p>
      <p>Password: <input type="password" name="pwd" value=""></p>
      <p>Confirm Password: <input type="password" name="cpw" value=""></p>
      <p>User Level: <select name="user_level"></p>
            <option value="admin">admin</option>
            <option value="normal">normal</option>
        </select>
        <input type="hidden" name="user_id" value="{{user.id}}">
        <p><input type="submit" name="submit"></p>
        <div class = 'container'>
            <div class = 'row'>
                <textarea name="desc" cols="90" rows="10"></textarea>
                <input type="submit" name="submit">
            </div>
        </div>
    </form>
  </body>
</html>

dashboard/apps/users/templates/users/edit.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User Dashboard Assignment</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css ">
  </head>
  <body>
    <nav class='navbar navbar-default'>
      <h1>User Dashboard</h1>
      <a href="/dashboard">Home</a>
      <a class = 'navbar-right' href="{%url 'users:logout'%}">Sign Out</a>
    </nav>
    <h1>Edit settings</h1>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    <form action="{% url 'users:update'%}" method="post">
      <div class = 'container'>
          {% csrf_token %}
        <div class = 'row'>
          <div class = 'col'>
            <p>First Name: <input type="text" name="first" value="{{user.first_name}}"></p>
            <p>Last Name: <input type="text" name="last" value="{{user.last_name}}"></p>
            <p>Email: <input type="email" name="email" value="{{user.email}}"></p>
            <p><input type="submit" name="submit"></p>
          </div>
          <div class = 'col'>
            <p>Password: <input type="password" name="pwd" value=""></p>
            <p>Confirm Password: <input type="password" name="cpw" value=""></p>
            <input type="hidden" name="user_id" value="{{user.id}}">
            <p><input type="submit" name="submit"></p>
          </div>
        </div>
      </div>
      <div class = 'container'>
        <div class = 'row'>
          <textarea name="desc" cols="90" rows="10"></textarea>
          <input type="submit" name="submit">
        </div>
      </div>
    </form>
  </body>
</html>

dashboard/apps/users/templates/users/login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User Dashboard Assignment</title>
  </head>
  <body>
    {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
              {{ message }}
          </li>
          {% endfor %}
      </ul>
    {% endif %}
    <h1>Login</h1>
    <form action="{% url 'users:login' %}" method="post">
      {% csrf_token %}
      {{login.as_p}}
      <!-- <p>Email: <input type="email" name="email"></p>
      <p>Password: <input type="password" name="pwd"></p> -->
      <input type="submit" name = 'login' value="Submit" />
    </form>
  </body>
</html>

dashboard/apps/users/templates/users/new.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User Dashboard Assignment</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css ">
  </head>
  <body>
    <nav class='navbar navbar-default'>
      <h1>User Dashboard</h1>
      <a href="/">Home</a>
      <a class = 'navbar-right' href="{%url 'udb:index'%}">Back</a>
    </nav>
    {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
              {{ message }}
          </li>
          {% endfor %}
      </ul>
    {% endif %}
    <h1>Register</h1>
    <form action="{% url 'users:create' %}" method="post">
      {% csrf_token %}
      {{register.as_p}}
      <!-- <p>First Name: <input type="text" name="first" value=""></p>
      <p>Last Name: <input type="text" name="last" value=""></p>
      <p>Email: <input type="email" name="email" value=""></p>
      <p>Password: <input type="password" name="pwd" value=""></p>
      <p>Confirm Password: <input type="password" name="cpwd" value=""></p> -->
      <input type="submit" name = 'register' value="Submit" />
    </form>
  </body>
</html>

dashboard/apps/users/templates/users/profile.html
<!DOCTYPE html>
<html>
  <head>
    {%load static%}
    <meta charset="utf-8">
    <title>User Dashboard Assignment</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css ">
  </head>
  <body>
    <nav class='navbar navbar-default'>
      <h1>User Dashboard</h1>
      <a href="/dashboard">Home</a>
      <a href="{% url 'users:show' id%}">My Profile</a>
      <a class = 'navbar-right' href="{%url 'users:logout'%}">Sign Out</a>
    </nav>
    <h2>{{user.first_name}} {{user.last_name}}</h2>
    <h5>Registered: {{user.created_at}}</h5>
    <h5>User ID: {{user.id}}</h5>
    <h5>Email: {{user.email}}</h5>
    <h5>Description: {{user.description}}</h5>
      
    <form action="post" method="post">
      {% csrf_token %}
      <textarea name="post" cols="90" rows="5"></textarea>
      <input type="hidden" name = "user_id" value = "{{user.id}}">
      <p><input type="submit" name="submit"></p>
    </form>
    {%for post in posts reversed%}
    <p >{{post.post}} - {{post.poster.first_name}} {{post.poster.last_name}} at {{post.created_at}}</p>
        <div class = 'container'>
          {%for comment in comments%}
            {%if comment.post.id == post.id%}
            <p>{{comment.comment}} - {{comment.commenter.first_name}} {{comment.commenter.last_name}} at {{comment.created_at}}</p>
            {%endif%}
          {%endfor%}
        </div>
          <form action="comment" method="post">
            {% csrf_token %}
            <textarea name="comment" cols="90" rows="2"></textarea>
            <input type="hidden" name = "post_id" value = "{{post.id}}">
            <input type="hidden" name = "user_id" value = "{{user.id}}">
            <p><input type="submit" name="submit"></p>
          </form>
    {%endfor%}
  </body>
</html>