dashboard/apps/udb/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^admin', views.admin, name = 'admin'),
    url(r'^dashboard', views.dashboard, name='dashboard'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^', views.index, name = 'index'),
]

dashboard/apps/users/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'show(?P<user_id>[0-9])', views.show, name = 'show'),
    url(r'delete/(?P<user_id>[0-9])', views.delete, name = 'delete'),
    url(r'update', views.update, name = 'update'),
    url(r'edit/(?P<user_id>[0-9])', views.edit, name = 'edit'),
    url(r'^create', views.create, name = 'create'),
    url(r'^login', views.login, name = 'login'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^new', views.new, name = 'new'),
    url(r'^signin', views.signin, name = 'signin'),
    url(r'^comment', views.comment, name = 'comment'),
    url(r'^post', views.post, name = 'post'),
]

dashboard/dashboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^users/', include('apps.users.urls', namespace = 'users')),
    url(r'^', include('apps.udb.urls', namespace = 'udb')),
]

dashboard/apps/udb/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponseRedirect, HttpResponse, redirect
from ..users.models import User

# Create your views here.
def index(request):
    #start the journey
    return render(request, 'udb/index.html')
def admin(request):
    #the admin's dashboard
    if request.session['level']<5:
        return redirect('/dashboard')
    else:
        id = request.session['id']
        user = User.objects.get(id = id)
        users = User.objects.all()
        context = {
            'id': id,
            'name': user.first_name,
            'users': users,
        }
        return render(request, 'udb/admin_dashboard.html', context)
def dashboard(request):
    #standard user's dashboard
    id = request.session['id']
    user = User.objects.get(id = id)
    users = User.objects.all()
    context = {
        'id': id,
        'name': user.first_name,
        'users': users,
    }
    return render(request, 'udb/dashboard.html', context)
def logout(request):
    del request.session['id']
    return redirect('/')

dashboard/apps/udb/templates/udb/admin_dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User Dashboard Assignment</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css ">
  </head>
  <body>
    <nav class='navbar navbar-default'>
      <h1>User Dashboard</h1>
      <a href="/">Home</a>
      <a class = 'navbar-right' href="{%url 'users:logout'%}">Sign Out</a>
    </nav>
    <h1>Welcome Back {{name}}</h1>
    <h2>All Users</h2>
    <table class = "table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Joined</th>
        <th>User Level</th>   
        <th>Actions</th>     
      {%for user in users%}
      </tr>
        <td>{{user.id}}</td>
        <td><a href="{% url 'users:show' user.id%}">{{user.first_name}} {{user.last_name}}</a></td>
        <td>{{user.email}}</td>
        <td>{{user.created_at}}</td>
        {%if user.user_level > 5%}
        <td>admin</td>
        {%else%}
        <td>normal</td>
        {%endif%}
        <td><a href="/users/edit/{{user.id}}">edit</a> <a href="/users/delete/{{user.id}}">delete</a></td>
      </tr>
      {%endfor%}
    </table>
    <a href="/logout">Logout</a>
  </body>
</html>

dashboard/apps/udb/templates/udb/dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User Dashboard Assignment</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css ">
  </head>
  <body>
    <nav class='navbar navbar-default'>
      <h1>User Dashboard</h1>
      <a href="/users/dashboard">Home</a>
      <a href="/users/edit/{{id}}">Edit</a>
      <a class = 'navbar-right' href="{%url 'users:logout'%}">Sign Out</a>
    </nav>
    <h1>Welcome Back {{name}}</h1>
    <h2>All Users</h2>
    <table class = "table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Joined</th>
        <th>User Level</th>        
      {%for user in users%}
      </tr>
        <td>{{user.id}}</td>
        <td><a href="{% url 'users:show' user.id%}">{{user.first_name}} {{user.last_name}}</a></td>
        <td>{{user.email}}</td>
        <td>{{user.created_at}}</td>
        {%if user.user_level > 5%}
        <td>admin</td>
        {%else%}
        <td>normal</td>
        {%endif%}
      </tr>
      {%endfor%}
    </table>
    <a href="/logout">Logout</a>
  </body>
</html>

dashboard/apps/udb/templates/udb/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User Dashboard Assignment</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css ">
  </head>
  <body>
    <nav class='navbar navbar-default'>
      <h1>Test App</h1>
      <a href="/">Home</a>
      <a class = 'navbar-right' href="{%url 'users:signin'%}">Sign in</a>
    </nav>
    <h1>Welcome to the Test</h1>
    <p>We're going to build a cool application using a MVC framework!
      This application was built with the Village88 folks!</p>
    <form action="{%url 'users:new'%}" method="post">
        {% csrf_token %}
      <input type="submit" name="start" value="Start">
    </form>

  </body>
</html>